version: 2.1

workflows: 
  test-deploy:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/node:14
    steps:
      - checkout
      - run: 
          name: install dependencies 
          command: npm install
      - run: 
          name: start npm
          command: npm run test
